name: CI
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d
      - name: Build
        run: |
          make build
      
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.0.5

      - name: Build and push docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo Logging Into Docker
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          echo Installing BuildX
          make setup-buildx
          echo Building Containers and Publishing them
          make img-buildx
          # make img-push
